services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.laravel # Point to the Laravel Dockerfile
        container_name: laravel_app
        ports:
            - "8000:8000" # Laravel dev server port
        volumes:
            - .:/app
            - /app/node_modules
            - ./storage:/app/storage # Add this line to link the storage folder

        working_dir: /app
        depends_on:
            - db
        environment:
            VITE_DEV_SERVER_URL: http://localhost:5173 # Vite dev server URL
        command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"] # Laravel serve command

    vite:
        build:
            context: .
            dockerfile: Dockerfile.vite # Point to the Vite Dockerfile
        container_name: vite_app
        ports:
            - "5173:5173" # Vite dev server port
        volumes:
            - .:/app
            - /app/node_modules
        working_dir: /app
        command: ["npm", "run", "dev"] # Vite dev command

    db:
        image: mysql:8
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
